Fix multiarch docker images
For reasons I cannot comprehend very well, we were copying the amd64 binary into the arm images.

I have now copy-pasted the github action code from Kubo even more than before,
and adapted the Dockerfile with changes that magically make things work even
though they shouldn't be necessary.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -5,6 +5,7 @@ on:
   push:
     branches:
       - 'master'
+      - 'docker-fixes'
     tags:
       - 'v*'
 
@@ -51,17 +52,72 @@ jobs:
           echo "EOF" >> $GITHUB_OUTPUT
         shell: bash
 
-      - name: Build Docker image and publish to Docker Hub
-        uses: docker/build-push-action@v4
+      # We have to build each platform separately because when using multi-arch
+      # builds, only one platform is being loaded into the cache. This would
+      # prevent us from testing the other platforms.
+      - name: Build Docker image (linux/amd64)
+        uses: docker/build-push-action@v6
         with:
-          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6
+          platforms: linux/amd64
           context: .
-          push: true
+          push: false
+          load: true
           file: ./Dockerfile
-          tags: "${{ steps.tags.outputs.value }}"
+          tags: ${{ env.IMAGE_NAME }}:linux-amd64
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache-new
 
+      - name: Build Docker image (linux/arm/v7)
+        uses: docker/build-push-action@v6
+        with:
+          platforms: linux/arm/v7
+          context: .
+          push: false
+          load: true
+          file: ./Dockerfile
+          tags: ${{ env.IMAGE_NAME }}:linux-arm-v7
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache-new
+
+      - name: Build Docker image (linux/arm64/v8)
+        uses: docker/build-push-action@v6
+        with:
+          platforms: linux/arm64/v8
+          context: .
+          push: false
+          load: true
+          file: ./Dockerfile
+          tags: ${{ env.IMAGE_NAME }}:linux-arm64-v8
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache-new        
+
+      # We test all the images on amd64 host here. This uses QEMU to emulate
+      # the other platforms.
+      # NOTE: --version should finish instantly, but sometimes
+      # it hangs on github CI (could be qemu issue), so we retry to remove false negatives
+      - name: Smoke-test linux-amd64
+        run: for i in {1..3}; do timeout 15s docker run --rm $IMAGE_NAME:linux-amd64 version && break || [ $i = 3 ] && exit 1; done
+        timeout-minutes: 1
+      - name: Smoke-test linux-arm-v7
+        run: for i in {1..3}; do timeout 15s docker run --rm $IMAGE_NAME:linux-arm-v7 version && break || [ $i = 3 ] && exit 1; done
+        timeout-minutes: 1
+      - name: Smoke-test linux-arm64-v8
+        run: for i in {1..3}; do timeout 15s docker run --rm $IMAGE_NAME:linux-arm64-v8 version && break || [ $i = 3 ] && exit 1; done
+        timeout-minutes: 1
+
+        # This will only push the previously built images.
+      - if: github.event_name != 'workflow_dispatch' || github.event.inputs.push == 'true'
+        name: Publish to Docker Hub
+        uses: docker/build-push-action@v6
+        with:
+          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
+          context: .
+          push: true
+          file: ./Dockerfile
+          tags: "${{ github.event.inputs.tags || steps.tags.outputs.value }}"
+          cache-from: type=local,src=/tmp/.buildx-cache-new
+          cache-to: type=local,dest=/tmp/.buildx-cache-new
+            
       # https://github.com/docker/build-push-action/issues/252
       # https://github.com/moby/buildkit/issues/1896
       - name: Move cache to limit growth
